### ISSUE TITLE
[Bug] PIN handle not working

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#34]
Typically, when you provide a wrong PIN 4 times, the card get blocked.
Here, with the mobile app, there is no such check.

First issue: 

- when you provide a wrong PIN code, the NFC toast message is not clear enough and you go back to the scan screen.
The best UX should be like this:
- you scan the card, you provide the PIN. If it's wrong, the toast tells you that with a specific message (red exclamation mark) and you can try another time (4 times).
The card should give you the PIN remaining status.

![msg531914946-233987](https://github.com/user-attachments/assets/326188ec-99bd-4f54-85f2-ae832130f5b1)

![image](https://github.com/user-attachments/assets/c9cad9b4-64a9-4c74-a1b8-2103af3bf01a)

Second issue:

- if a card is blocked - meaning you entered too many wrong PIN, there is no message. 
The user is not informed that he had blocked his card.

Please update this process to make it more clear. If the card give a "blocked" status back, the user should be notified through -either a pop up - or the NFC toast message - that the card is blocked.

![image](https://github.com/user-attachments/assets/3bcbf1c8-3ce1-4917-bec3-39396e320435)

**Comment by Toporin** [comment]
The issue is not completely solved:

Correct: When a wrong PIN is entered, a message showing wrong PIN with number of remaining tries is displayed

However, when the card is blocked the message "wrong PIN code" is shown instead of "Too many wrong PIN! Card is blocked."
When number of PIN remaining is 0, the message "Too many wrong PIN! Card is blocked." should be shown.


![photo_5868321822523638481_y](https://github.com/user-attachments/assets/98e7cb71-b6e2-4750-a058-48047d6a91a3)
![photo_5868321822523638482_y](https://github.com/user-attachments/assets/fd8be8cc-b9f7-43f5-97eb-b2f830c12d0b)
![photo_5868321822523638483_y](https://github.com/user-attachments/assets/43d2eeb8-c783-4ac5-a749-89794d75b887)
![photo_5868321822523638484_y](https://github.com/user-attachments/assets/5b55622f-d8ff-456c-9122-fcc0c2c36019)
![photo_5868321822523638485_y](https://github.com/user-attachments/assets/f1bfeeb1-c71c-4b28-a32b-2dce75302265)

**Comment by Bastien-Satochip** [comment]
Tested and fixed.
