### ISSUE TITLE
[Improvment] Memorable passwords

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#44]
Please add a "Memorable" password option while generating a password.

We can use this list: https://github.com/sts10/generated-wordlists/blob/main/lists/1password-replacement/1password-replacement.txt

The lenght of the password should allow the user to select from 4 to 16. But if "Memorable password" is set ON, the size become from 4 WORDS to 16 WORDS (not 4 char to 16 char).

A memorable password example: https://1password.com/password-generator/ (select "Memorable)

**Comment by Toporin** [comment]
When memorable is set, number of words should be between **4** and 16.
Moreover, user **should also be able to select upper case, number and symbols**: if upper case is on, the first letter of each word is Uppercase; if numbers and/or symbol is set, corresponding random char is placed between words (instead of default dash '-')

See memorable password example: https://1password.com/password-generator/ (select "Memorable)

For example on android:
![photo_5868321822523638465_y](https://github.com/user-attachments/assets/5997f5d0-a71c-441b-a716-fec276879f25)

**Comment by Bastien-Satochip** [comment]
Tested and fixed.
